# Generated by Django 3.2.12 on 2022-04-18 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_adress', models.CharField(max_length=100)),
                ('city_adress', models.CharField(max_length=50)),
                ('cp_adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_creator', models.CharField(max_length=50)),
                ('firstname_creator', models.CharField(max_length=50)),
                ('birthdate_creator', models.DateField(verbose_name='Date de naissance du createur')),
                ('avatar_creator', models.ImageField(blank=True, upload_to='pictures_creator')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_layout', models.CharField(max_length=50)),
                ('number_layout', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_publication', models.CharField(max_length=50)),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('description_publication', models.TextField(blank=True, null=True)),
                ('pictures_publication', models.ImageField(blank=True, upload_to='Pictures_publication')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_typeLayout', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_user', models.ImageField(blank=True, upload_to='Avatar')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('note', models.IntegerField(choices=[(1, 'Mauvais'), (2, 'Faible'), (3, 'Moyen'), (4, 'Intéressant'), (5, 'Incroyable !')], default=0)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ManyToManyField(to='discover.SubCategory'),
        ),
        migrations.AddField(
            model_name='publication',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discover.creator'),
        ),
        migrations.AddField(
            model_name='publication',
            name='layout',
            field=models.ManyToManyField(blank=True, to='discover.Layout'),
        ),
        migrations.AddField(
            model_name='publication',
            name='users',
            field=models.ManyToManyField(blank=True, through='discover.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layout',
            name='type_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.typelayout'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.publication'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creator',
            name='statut',
            field=models.ManyToManyField(to='discover.Statut'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
                ('avatar_category', models.ImageField(blank=True, upload_to='pictures_category')),
                ('subcategory', models.ManyToManyField(to='discover.SubCategory')),
            ],
        ),
    ]
